name: CLGSDN
memory_type: LPM
n_feat: 4
n_GMB: 4
n_prob: 3
sparity_rate: 0.02
loss_rate: 2.5
graph_noise: 0.225
gamma: [-0.3,1.4]
n_channels: 4
attn_hid_dim: 32
local_obs: True
global_obs: True
simi_type: TDA
dist_type: dist
feat_cl_loss: True
prob_cl_loss: True
identity_topo: False
LPM_learnable: True
data_channels: 1
feat_filter: True
prob_filter: True
filter_attn: True